### ISSUE TITLE
Buttin in App Bar doesn't work

### ISSUE THREAD

**Issue by abenhamdine** [marmelab/admin-on-rest-demo#10]
Browser : Version 56.0.2924.87 (64-bit)
Windows 10 64 bits

I checked out the repo yesteday, ran npm build then start.

When I click the App Bar button, nothing happens, the menu isn't folded.  

![image](https://cloud.githubusercontent.com/assets/7466144/23586771/eaf8c3c2-019c-11e7-9418-48b7c802bccd.png)

In the same browser, on the url https://marmelab.com/admin-on-rest-demo/, it works perfectly.

**Comment by fzaninotto** [comment]
This is because the folding code is in the `next` branch of admin-on-rest. This will be solved when we release the 0.9 version.

**Comment by abenhamdine** [comment]
ahhh yes, thx for you quick answer ! When do you plan to release it ?

**Comment by fzaninotto** [comment]
about March, 12th.

**Comment by abenhamdine** [comment]
Thx.
