### ISSUE TITLE
What is the folder structure philosphy?

### ISSUE THREAD

**Issue by daumann** [marmelab/admin-on-rest-demo#16]
Hi @fzaninotto and congrats to this awesome framework! Could you say a few words about how you approach folder structure in this demo application?

I am a bit confused because I don't see the usual React/ Redux folders _containers, components, reducers_, ... etc.

Adding a paragraph to the README would probably be best. 

I am happy that I found this framework last night... will save me a lot of time ;-)

**Comment by djhi** [comment]
Hi, this article from our blog should answer your question: https://marmelab.com/blog/2015/12/17/react-directory-structure.html.

In a nutshell, we prefer to structure things by domain rather than technical uses

**Comment by daumann** [comment]
@djhi exactly what I was looking for, thanks!
