### ISSUE TITLE
aor List pages error. Nan-Nan of *

### ISSUE THREAD

**Issue by arcsecw** [marmelab/admin-on-rest-demo#17]
NaN-Nan of *(perPage) error appear in pages of Customers List or Posters List or Customers List 
Those page's url  has parm "filter" 
![image](https://user-images.githubusercontent.com/10559820/26938623-5213005e-4ca7-11e7-8758-9f739d0becc8.png)

At the same time ,a List page without parm "filter" is normal
![image](https://user-images.githubusercontent.com/10559820/26938656-71ce62c6-4ca7-11e7-88fc-006960b7bf10.png)

1.  Add &page=1 to those page can solve this problem
2.  modify code like this 
![image](https://user-images.githubusercontent.com/10559820/26938574-259f1256-4ca7-11e7-9b9e-79649dfb9041.png)
3.  modify admin-on-rest

**Comment by Jonathan-Rosewood** [comment]
Damn.
Too find this bug 5 minutes ago :)

**Comment by arcsecw** [comment]
I think this bug caused by aor  List  component
at src/mui/list/List.js
![image](https://user-images.githubusercontent.com/10559820/26958095-599fa5a8-4cfb-11e7-991f-0826ffd7ab28.png)
when the page is undefined parseInt(page,10) = NaN

**Comment by fzaninotto** [comment]
I can't reproduce it on the demo.

![image](https://user-images.githubusercontent.com/99944/27040996-f8bb4194-4f92-11e7-8bb9-0df251f403e2.png)

Which version of aor are you using? Can you describe the test scenario in more detail?

**Comment by NikitaVlaznev** [comment]
You can see it in demo [there](https://marmelab.com/admin-on-rest-demo/#/customers?filter=%7B%22groups%22%3A%22compulsive%22%7D), for example.

It seems that bug appears when there is only 1 element in the filtered list.

Here is a screen from the demo page:
![image](https://user-images.githubusercontent.com/8362867/27052262-d18cf17e-4fc1-11e7-87d3-23e5012cc6e2.png)

**Comment by NikitaVlaznev** [comment]
Why not to use perPage setting that is passed to the List component by default?
