### ISSUE TITLE
demo not working on Android?

### ISSUE THREAD

**Issue by StefanScott** [marmelab/admin-on-rest-demo#20]
This framework admin-on-rest is very nice - and could become an important tool for developers.

I have been testing the on-line demo on Android, using two different browsers: Chrome and the "built-in" browser on Android (I think it's IceWeasel - the icon is a world globe with light-blue water and white land).

On both browsers, I was able to login to the admin-on-rest-demo - but then there appeared only a blank white screen.

Meanwhile, on a Windows desktop screen (tested in Chrome and Firefox), the program was partially "responsive": 

- When I used the mouse to make the window very narrow, the site navigation menu worked perfectly.

- List views were partially responsive: the data grid appeared, but only the left-mose columns. It was not possible to click the "Edit" buttons, because they were on the right side. Two "quick fixes" for this might be: 

   - Moving the "Edit" buttons to the left-most column (at the start of each row), so they would always be accessible.

   - Making the item in the left-most column clickable (eg, make the Customer Name a link, to navigate to the "Edit Customer" screen).

admin-on-rest is an excellent front-end, and I believe that Material-UI generally does work on mobile, so I hope we can get admin-on-rest to work nicely on Android (and iOS, which I haven't tested).

**Comment by djhi** [comment]
Thank you for the kind words and for reporting this.

Admin-on-rest does support mobile as you can see in the [documentation](https://marmelab.com/admin-on-rest/List.html#the-simplelist-component) with specific components tailored for small devices. However we didn't apply them in the demo.

This demo application definitely needs to be updated !

**Comment by StefanScott** [comment]
Thanks for this info!
