### ISSUE TITLE
..Loading, white page

### ISSUE THREAD

**Issue by elektron4** [marmelab/admin-on-rest-demo#23]
HI!
Sample demo in web looks very cool.
I test it in my localhost (made npm install, npm start)
But get only white screen with text "Loading", some errors in console. 
![image](https://user-images.githubusercontent.com/25268478/30514849-02f1a12e-9b26-11e7-9583-6eb3618e4cc6.png)

**Comment by djhi** [comment]
You are referring to the [admin-on-rest-graphql-demo](https://github.com/marmelab/aor-graphql/tree/master/packages/admin-on-rest-graphql-demo), aren't you ?

Please open the issue in its repository
